### ISSUE TITLE
[Bug] API `guild.member.mute` 中禁言时长转换错误

### ISSUE THREAD

**Issue by wyf7685** [wyapx/nekobox#3]
https://github.com/wyapx/nekobox/blob/main/src/nekobox/apis/handler.py#L130

`guild_member_mute` 函数中将传入的禁言时长从毫秒转换为秒，但错误地使用了  `* 1000` ( 应为 `/ 1000` )

nekobox 版本: [9058efa](https://github.com/wyapx/nekobox/tree/9058efa)

**Comment by wyapx** [comment]
收到，现在正在检查

**Comment by wyapx** [comment]
~~睡迷糊了~~感谢反馈
